### ISSUE TITLE
E-Mail Notification for locations

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commons-booking#143]
BCC of Booking Confirmation to stations.

**Comment by sgrubsmyon** [comment]
Hi, at Bolle Bonn (https://bolle-bonn.de), we are currently switching to using the CB plugin. We are very interested in this feature because our booking stations usually want to be informed who is coming when to grab the item.

I would be willing to help in the implementation. Do you need any support?

Cheers!

**Comment by flegfleg** [comment]
Hey @sgrubsmyon, that´s great! Yes, support would be great :) 
I am currently working to re-organise the plugin files & classes so contributing will be easier (2/3 of the frontend are done). Will hopefully be finished in september.

**Comment by sgrubsmyon** [comment]
@flegfleg: Does that mean I should wait until you finished the re-organisation?
@anewholm: What have you done so far? I don't want to interfere with your work.

**Comment by sgrubsmyon** [comment]
Any updates on this? I see that there is a branch for the issue: https://github.com/wielebenwir/commons-booking/compare/email_notification_for_locations. I will try to use it and test if it works OK.

**Comment by flegfleg** [comment]
Hey, unfortunately not right now. Still working on it. Hope this month.

**Comment by sgrubsmyon** [comment]
Please note that I have implemented this here: https://github.com/sgrubsmyon/commons-booking/tree/email_notification_for_locations and merged it into the master branch at https://github.com/sgrubsmyon/commons-booking/tree/master. The way it is implemented (similar to https://github.com/wielebenwir/commons-booking/tree/email_notification_for_locations) is by using a regex to extract all email addresses from the contact information field of the location. Like before, an email is sent to the user and the global BCC address, afterwards emails are sent to all the location email addresses found. I also implemented email delivery in case of booking cancellation here: https://github.com/sgrubsmyon/commons-booking/tree/email_on_cancel.

What I would like to still add: Check boxes in the settings that switch the email delivery to locations on and off.

**Comment by sgrubsmyon** [comment]
Update: there is now a check box to switch on/off the BCC email delivery to a location. See PR https://github.com/wielebenwir/commons-booking/pull/172 or https://github.com/sgrubsmyon/commons-booking/commit/70e875c4ee8a57b20b16c103bc92f18b0626a551.

**Comment by sgrubsmyon** [comment]
New update: Notification emails will also be sent when an admin deletes a booking from the booking table (only if the booking was not already canceled by the user and lies in the future). See https://github.com/wielebenwir/commons-booking/pull/172 and https://github.com/sgrubsmyon/commons-booking.
