### ISSUE TITLE
Missing <li> in widget

### ISSUE THREAD

**Issue by flegfleg** [wielebenwir/commons-booking#149]
"Du bist nicht eingeloggt.Einloggen":

**Comment by niccokunzmann** [comment]
I see that everything is in a li. (Source)[https://github.com/wielebenwir/commons-booking/blob/0aa12d1851606f70fb623fda85f917bceea34468/admin/cb-widgets/cb-user-widget.php#L105]

**Comment by 1resu** [comment]
@flegfleg I think the problem belongs to the kasimir theme. Comment line 1618 in style.css (display: inline) and it'll work.

**Comment by flegfleg** [comment]
Yes, it´s in the theme. 
Thanks @1resu!
