### ISSUE TITLE
Booking code / Schlossnummer

### ISSUE THREAD

**Issue by LeDisciple** [wielebenwir/commons-booking#150]
Hallo, 
wir möchten bei der Buchungsbestätigung / E-Mail Bestätigung eine Schlossnummer angeben. 
Die Codes sind automatisch generiert. Falls man sie manuell ändern könnte, wäre es eine Lösung / einen Workaround. 
Als Workaround habe ich die Schlossnummer in den Kontaktdaten für die Location eingebene, mit Option erst nach Buchung anzuzeigen. Allerdings ist die Nummer dann nur in der Buchungsbestätigung zu sehen, nicht in der E-Mail Bestätigung. Wäre es nicht sowieso Sinnvoll die Kontaktdaten der Location / des Items auch in die E-Mails einzugeben ?
Danke!
Denis von FreiRad Bamberg

**Comment by LeDisciple** [comment]
Update: 
inzwischen habe ich verstanden, wie die Contact-Infos in der E-Mail template zu ergänzen sind. 
Der Workaround funktioniert, obwohl Item-Informationen (Schloss-Nummer) über die Standort-Informationen (Contact) übermittelt werden. 
Ist hiermit abgeschlossen. Das Thema werde ich bei der anderen Feature request bei Bedarf  aktualisieren. 
Danke!

**Comment by flegfleg** [comment]
Hallo Denis, 
zur Benutzerfreundlichkeit sollte das Standard-Template natürllich alle Tags enthalten. Hab das festgehalten: https://github.com/wielebenwir/commons-booking/issues/153

**Comment by LeDisciple** [comment]
Super, danke!

Denis

Am 22.05.2017 um 18:04 schrieb Florian Egermann:
