### ISSUE TITLE
Booking on closed days possible

### ISSUE THREAD

**Issue by consoleiro** [wielebenwir/commons-booking#155]
Booking on all days, even on closed days is since the update to 0.9.2.11 possible. I've tried create an new location and object, new installation, changed max from 3 to 2, deleted the code from database on this day, but nothing fixed the issue. For testing i've created an new item https://lastenrad-wuerzburg.de/cb-items/long-john/ with only one openend day, but its on all days possible.

**Comment by flegfleg** [comment]
Hi @consoleiro , 
sorry to hear there´s an issue. 
i am on holidays right now, will look into it on tuesday. 
Best!

**Comment by nillerdk** [comment]
I can confirm this issue. Downgrade to version 0.8.0.10 was easily possible with the plug-in "WP-Rollback". Be careful, downgrade from 0.9.2.11 to other versions than 0.8.0.10 failed!

**Comment by flegfleg** [comment]
Found it. Should be fixed in 0.9.2.12.
https://github.com/wielebenwir/commons-booking/releases/tag/0.9.2.12
Can you confirm? Will upload to WP.org afterwards. 
Thanks for reporting!
Flo

**Comment by nillerdk** [comment]
Yeah, with 0.9.2.12 the closing days are shown again - thanks! I think there is still a related (?) issue (settings: "Buchung über geschlossene Tage" checked, "zählweise für ..." unchecked):
- I can book from Thursday to Monday when Saturday *and* Sunday are closing days -> OK
- I can book from Thursday to Sunday when only Saturday a closing day is -> OK
- I can't book from Friday to Monday when only Sunday a closing day is -> NOT EXPECTED, I get the error "bitte wähle aufeinanderfolgende Tage aus".

Btw: the descriptions for the two options "Buchung über geschlossene Tage" and "zählweise für ..." could be formulated clearer (German version, I haven't checked the English). It is hard to understand the intention. I will think about an improvement.

**Comment by flegfleg** [comment]
> I can't book from Friday to Monday when only Sunday a closing day is -> NOT EXPECTED, I get the error "bitte wähle aufeinanderfolgende Tage aus".

OK, i am quite sure this is not directly related, it´s a js validation issue. Closing this one and releasing a fix for the main issue on WP.org. 

> Btw: the descriptions for the two options "Buchung über geschlossene Tage" and "zählweise für ..." could be formulated clearer (German version, I haven't checked the English). It is hard to understand the intention. I will think about an improvement.

i agree ;) Better wording is very welcome.
