### ISSUE TITLE
Codes Generation

### ISSUE THREAD

**Issue by Konafets** [wielebenwir/commons-booking#175]
Hi, 

we have a special case of code generation. Instead of words or sentences we need a 4-digits number for a [key safe](https://www.burg.biz/p/geldkassette-schluessel/schluesselbox-schluesseltafel/schluesseltresor-key-safe/). The number rotates every week, meaning it stays the same for 7 days.

I generated a list of numbers and placed them into the codes form in the admin section. Unfortunately this did not worked out:

- The code list started with some sentences which seems to be hardcoded inside the plugin. I would expect that the plugin takes my codes and not some hidden ones
- The numbers are shuffled, which makes it impossible to have the same number for one week.

 
Generated numbers
```
2248,2248,2248,2248,2248,2248,2248,2913,2913,2913,2913,2913,2913,2913,2502,2502,2502,2502,2502,2502,2502,5802,5802,5802,5802,5802,5802,5802,1399,1399,1399,1399,1399,1399,1399,6465,6465,6465,6465,6465,6465,6465,6219,6219,6219,6219,6219,6219,6219,2005,2005,2005,2005,2005,2005,2005,1807,1807,1807,1807,1807,1807,1807,1438,1438,1438,1438,1438,1438,1438,7242,7242,7242,7242,7242,7242,7242,...
```

How is it possible to take only my codes and don't shuffle them?

**Comment by flegfleg** [comment]
Hm, the shuffling is part of the design…
your only choice right now (at least until cb2.0 arrives) is to edit the code directly. 

https://github.com/wielebenwir/commons-booking/blob/93ea40bf94ea8dfbca781ea0b49c1e0b257db4a0/admin/cb-codes/includes/class-cb-codes-generate.php#L86

replace with something like (untested):

`    // create mysql query
    for ( $i=0; $i < $count; $i++ ) {
      array_push($sqlcontents, '("' . $this->item_id. '","' . $this->missing_dates[$i]['date'] . '","' . $this->codes_array[ $i ] . '")');
`

**Comment by Konafets** [comment]
I archived this doing an CSV export of the codes tables, imported it into OO, changed the codes of the required location and imported back to the DB.
