### ISSUE TITLE
password reset email not sent with Wordpress 5.3+

### ISSUE THREAD

**Issue by poilu** [wielebenwir/commons-booking#180]
When a user clicks on the button to request a password reset link a redirect to the home page happens and the email is not sent. It seems that in newer versions of Wordpress the 'profile_update' action got triggered when processing this request. Due to the hook in the following line sending the email is skipped.

https://github.com/wielebenwir/commons-booking/blob/00c25e728745a45af589e64c5874d3133ed2c131/public/class-commons-booking.php#L152

**Comment by poilu** [comment]
In the commit just the method is deleted. The reference in add_action is still present. This leads to a PHP warning: `call_user_func_array() expects parameter 1 to be a valid callback, class 'CB_Users' does not have a method 'cb_user_profile_redirect'`

**Comment by flegfleg** [comment]
Oh, thanks for catching that! Will fix!

**Comment by flegfleg** [comment]
I drafted a new release for testing: 

https://github.com/wielebenwir/commons-booking/releases/tag/0.9.4.4

**Comment by poilu** [comment]
https://github.com/wielebenwir/commons-booking/blob/3b74d7aa2ae1e2b4bdb69c6b5109796fbbc99c05/public/class-commons-booking.php#L152 causes an error, because the array has too many members.

`add_action( 'profile_update', array( $this->users, 'cb_user_profile_redirect'), 12 );` would be correct, but doesn't solve the problem of not sending the email.

**Comment by flegfleg** [comment]
Are you using some smtp-plugin or the WordPress Mail function?

**Comment by poilu** [comment]
Yes, that's the case. It's https://de.wordpress.org/plugins/easy-wp-smtp/

**Comment by flegfleg** [comment]
OK, it was unrelated to the plugin. Have a new release: https://github.com/wielebenwir/commons-booking/releases/tag/0.9.4.6

**Comment by poilu** [comment]
Thanks, it's the expected behaviour now.

**Comment by sgrubsmyon** [comment]
Sorry, but this does not work for us at bolle-bonn.de. I see on kasimir-lastenrad.de, that the HTML of the password lost form differs. You have:
```
<form name="lostpasswordform" id="lostpasswordform" action="/user/lostpassword/" method="post">
    <p class="tml-user-login-wrap">
        <label for="user_login">Benutzername oder E-Mail:</label>
        <input type="text" name="user_login" id="user_login" class="input" value="" size="20">
    </p>
    <p class="tml-submit-wrap">
        <input type="submit" name="wp-submit" id="wp-submit" value="Neues Passwort beantragen">
        <input type="hidden" name="redirect_to" value="https://www.kasimir-lastenrad.de/user/login/?checkemail=confirm">
        <input type="hidden" name="instance" value="">
        <input type="hidden" name="action" value="lostpassword">
    </p>
</form>
```
Important is the last hidden input, since @flegfleg's patch (https://github.com/wielebenwir/commons-booking/commit/a9687b7f81a6d651acd2a763617cf6d3a6e24073) looks for the posted data named "action" with value "lostpassword".

On bolle-bonn.de, we don't have this. We have:
```
<form name="lostpassword" action="https://bolle-bonn.de/lostpassword" method="post">
    <div class="tml-field-wrap tml-user_login-wrap">
        <label class="tml-label" for="user_login">Benutzername oder E-Mail-Adresse</label>
        <input name="user_login" type="text" value="" id="user_login" class="tml-field">
    </div>
    <div class="tml-field-wrap tml-submit-wrap">
        <input name="submit" type="submit" value="Neues Passwort" class="tml-button">
    </div>
    <input name="redirect_to" type="hidden" value="">
</form>
```
This creates a POST request with this data:
```
user_login:	"<username_entered_into_form>"
submit:		"Neues+Passwort"
redirect_to:	""
```
So no "action" in the data. Therefore, it does not work.

I see that Kasimir uses the "Theme My Login" plugin (there are CSS classes "tml-..."). We also use it, but HTML is still different.

Why is there no universal way to detect a password reset in WordPress, independent of site configuration?

**Comment by mega-stoffel** [comment]
it looks like we don't have the hidden input with "action" either in our code and we don't use "Theme My Login".
But the lost password eMail is send out - just tested it successfully with the latest WP and CB versions.
Greetings from Stuttgart! :-)

**Comment by sgrubsmyon** [comment]
Maybe you don't have the most recent WordPress? @poilu indicated that it's only a problem in newer WordPress versions (since password reset works different). I think, but am not sure, that we didn't have the issue before upgrading to WordPress 5.4.

**Comment by flegfleg** [comment]
Hi guys, 

> Why is there no universal way to detect a password reset in WordPress, independent of site configuration?

there is, [the hook should](https://developer.wordpress.org/reference/hooks/password_reset/) fire regardless of the theme template, tml… etc. 

@sgrubsmyon: Still having issues? which version of WP are you using?

**Comment by sgrubsmyon** [comment]
@flegfleg How does the hook, or action, you mentioned help to solve the problem?

The point is that a different action, which is added at https://github.com/wielebenwir/commons-booking/blob/master/public/class-commons-booking.php#L152, fires as well and when it fires, there seems no universal way to detect that the reason it was fired was the password reset.

The if line you added at https://github.com/wielebenwir/commons-booking/blob/master/admin/cb-users/class-cb-users.php#L239 seems specific to your site's (kasimir-lastenrad.de) configuration/theme/template and does not work everywhere.

> @sgrubsmyon: Still having issues? which version of WP are you using?

Yes. We are on WordPress 5.4.

**Comment by sgrubsmyon** [comment]
I think a workaround could be to modify the TML theme to resemble that of kasimir-lastenrad.de. There's a number of possible locations for the theme file, as described [here](https://docs.thememylogin.com/article/95-templates), but I can't find any template file concerning the lostpassword form in my WordPress install. I don't understand how the form is generated at all and how to influence the form to add the hidden input that is required.

**Comment by flegfleg** [comment]
@sgrubsmyon TML is not required, or any customising of the pw reset/login screen. 

> Yes. We are on WordPress 5.4.

and what exactly is not working? do you use any smtp plugin?

**Comment by nelarsen** [comment]
Did you see my comment to a related issue? I think especially about the second part. The syntax was already fixed (thanks @flegfleg). I think it is the exit()-call in the cb_user_profile_redirect-function causing problems. Maybe you should also try to remove the redirect line and see if you like the behaviour.
https://github.com/wielebenwir/commons-booking/issues/179#issuecomment-609015137

**Comment by sgrubsmyon** [comment]
@nelarsen Wow, thanks! Your comment was so much helpful! Both of your suggestions work fine: Removing the `exit;` from `cb_user_profile_redirect()` in `admin/cb-users/class-cb-users.php` or removing the line `add_action( 'profile_update', array( $this->users, 'cb_user_profile_redirect'), 12);` from `public/class-commons-booking.php`. I decided to remove the `exit;` since it seemed like the less intrusive change (maybe?).

@flegfleg You don't read me, do you?

> and what exactly is not working?

I explained it all here in detail: https://github.com/wielebenwir/commons-booking/issues/180#issuecomment-619417531

> do you use any smtp plugin or other specials?

As far as I know, we do not use any smtp/email specials. Didn't you conclude yourself in https://github.com/wielebenwir/commons-booking/issues/180#issuecomment-611747555 that the smtp plugin was unrelated to the bug?

**Comment by flegfleg** [comment]
Hi, thanks for your comments! 
Expecting the same actions to be present on every form was not ideal, thanks for pointing that out! 

I think this solution should be much more robust, tested with TML installed. 

Please let me know if that works for you: 
https://github.com/wielebenwir/commons-booking/blob/a7699bb87ec49dc36e1515552a0a7b934256eba2/admin/cb-users/class-cb-users.php#L237

As a [Zip](https://github.com/wielebenwir/commons-booking/releases/tag/0.9.4.8)

**Comment by sgrubsmyon** [comment]
@flegfleg Yes! It works beautifully! And the code is much simpler and understandable now. Thanks for fixing this. I will install version 0.9.4.8 online when it has propagated to the WordPress plugin repository.

**Comment by mega-stoffel** [comment]
> @mega-stoffel Maybe you don't have the most recent WordPress? @poilu indicated that it's only a problem in newer WordPress versions (since password reset works different). I think, but am not sure, that we didn't have the issue before upgrading to WordPress 5.4.

we do have the latest Wordpress version, which was 5.4 by that time. It automatically upgraded to 5.4.1 in the meantime.
And we were running the 0.9.4.7 CB-plugin, which was the latest one at that time.
But it looks like we have to test again with the newest CB-version.

**Comment by sgrubsmyon** [comment]
After installing version 0.9.4.8 of commons-booking, password reset email is sent out again also on our site.
