### ISSUE TITLE
Registration: always the same start password will be assigned

### ISSUE THREAD

**Issue by RainerBielefeld** [wielebenwir/commons-booking#181]
I had to do some tests because there were some (probably wrong) complaints concerning problems with Registration of new accounts for [heinrich-der-lastenloewe.de](https://www.heinrich-der-lastenloewe.de/). 

**Bad**:
I observed that I always received the same "very strong" default password for my own registration in 2017 and for my 2 new test accounts this weekend.

I think it is a very bad Idea to assign always the same password. The hint "strong" might prompt inexperienced users to keep that password.

General Software problem or something wrong with that particular application for heinrich-der-lastenloewe.de?

**Comment by flegfleg** [comment]
Hi, that IS weird :) 
cb1 does not generate the password, WP does. What version of cb1 are you using?

* do you have an additional plugin installed (theme my login, wp members, ...) that may influence password generation?

**Comment by RainerBielefeld** [comment]
Hi,
the page seems to use Common-Booking 0.9.4.2, at least 0.9.4.2 is very often mentioned in the source code, and the page shows the "Password Reset does not send Email"-Bug.
I can't answer the other questions, because I'm not site owner or admin of heinrich-der-lastenloewe.de

**Comment by RainerBielefeld** [comment]
The ADFC team just updated to 0.9.4.3 to eliminate the "Password Reset does not send Email" problem.

**Comment by flegfleg** [comment]
Please let us know if that solves the problem. 
Thanks!
