### ISSUE TITLE
uninstallation does not work

### ISSUE THREAD

**Issue by craiten** [wielebenwir/commons-booking#188]
When uninstall the commons booking plugin, I get this error:

> Löschen fehlgeschlagen: Es gab einen kritischen Fehler auf deiner Website.Erfahre mehr über die Fehlerbehebung in WordPress.

I guess it has to do with the uninstall hook but I am not curtain. I tried that local and on a server site. Both produce the same output.

**Versions:**
common-bookings: 0.9.4.13
Wordpress:  5.5.3

**Comment by flegfleg** [comment]
Hi, 
i could not reproduce that. 
Does the error happen on deactivation or deletion?
Best, Flo

**Comment by craiten** [comment]
It happens on deletion. 

I checked the permissions locally which look good to me:

> $ stat -c '%a %n' *
> 755 admin
> 755 assets
> 644 commons-booking.php
> 755 includes
> 644 index.php
> 644 LICENSE.txt
> 755 public
> 644 README.md
> 644 readme.txt
> 755 templates
> 644 uninstall.php

I installed the plugin via downloading it from the repo here (master branch) and uploading it via the wordpress plugin installation interface under `Plugins -> Install -> Upload plugin`. Could that cause the problem?

**Comment by flegfleg** [comment]
Hi!

> I installed the plugin via downloading it from the repo here (master branch) and uploading it via the wordpress plugin installation interface under Plugins -> Install -> Upload plugin. Could that cause the problem?

Seems unlikely. We are busy with CB2 right now, but I put it on the list for the next maintenance release, and i will post here if i need more info/we have a fix. 

Thanks again for pointing it out!
Flo

**Comment by flegfleg** [comment]
Hi, i found the error. 
The uninstall script was never used to delete any data, so we have removed the uninstaller. 
Pre-Release here: 
https://github.com/wielebenwir/commons-booking/releases/tag/0.9.4.14
