### ISSUE TITLE
uninstall fails with fatal error

### ISSUE THREAD

**Issue by chriwen** [wielebenwir/commons-booking#189]
the uninstall.php is still existent in current version
https://plugins.trac.wordpress.org/browser/commons-booking/tags/0.9.4.14 although it was mentioned as resolved in this release.

this files throws an array on deleting the plugin.
Löschen fehlgeschlagen: .wp-die-message { display: none; } Fatal error: Uncaught Error: Too few arguments to function WP_Roles::remove_cap(), 1 passed in /Applications/MAMP/htdocs/cb01/wp-content/plugins/commons-booking/uninstall.php on line 121 and exactly 2 expectedin /Applications/MAMP/htdocs/cb01/wp-includes/class-wp-roles.php on line 227Call stack:WP_Roles::remove_cap()wp-content/plugins/commons-booking/uninstall.php:121include_once()wp-admin/includes/plugin.php:1262uninstall_plugin()wp-admin/includes/plugin.php:967delete_plugins()wp-admin/includes/ajax-actions.php:4581wp_ajax_delete_plugin()wp-includes/class-wp-hook.php:292WP_Hook::apply_filters()wp-includes/class-wp-hook.php:316WP_Hook::do_action()wp-includes/plugin.php:484do_action()wp-admin/admin-ajax.php:187Query MonitorEs gab einen kritischen Fehler auf deiner Website.Erfahre mehr über die Problembehandlung in WordPress.

**Comment by flegfleg** [comment]
Fixed in 0.9.4.16
