### ISSUE TITLE
Export creates an empty file

### ISSUE THREAD

**Issue by babeene** [wielebenwir/commons-booking#191]
I wanted to export all time frames via Settings/Export. I tried different time periods, but the generated files were always empty (0 KB in size). There are entries under Bookings.

Used version: Version 2.6.12

![2022-04-03-ExportFailed](https://user-images.githubusercontent.com/54151884/161438869-1c03ae5f-e13f-4acc-ae00-dc15af1349d2.png)

**Comment by flegfleg** [comment]
Hey @babeene, sorry you are having issues. 
This is the repo/issues for CommonsBooking 0.9X (legacy). Unfortunately i cannot move your issue, can you copy + paste it to the [repository for the current CommonsBooking](https://github.com/wielebenwir/commonsbooking/issues)?

**Comment by babeene** [comment]
Hi @flegfleg, it seems that the problem is allready known under the current CommonsBooking version -> https://github.com/wielebenwir/commonsbooking/issues/939
There was a comment, that the fix was allready done in the master, must that only deployed?
